In [1]:
# 读取训练数据, 训练集包含500个模型结构，以及这些结构在cplfw，market1501，dukemtmc等8个任务上的性能排序
import json
with open('./data/CVPR_2022_NAS_Track2_train.json', 'r') as f:
    train_data = json.load(f)
print(train_data['arch1'])
print('train_num:',len(train_data.keys()))

{'cplfw_rank': 9, 'market1501_rank': 361, 'dukemtmc_rank': 426, 'msmt17_rank': 433, 'veri_rank': 327, 'vehicleid_rank': 480, 'veriwild_rank': 425, 'sop_rank': 367, 'arch': 'l231131331121121331111211121331321321'}
train_num: 500


In [2]:
import pandas as pd
import numpy as np

In [3]:
target_cols = ['cplfw_rank', 'market1501_rank', 'dukemtmc_rank', 'msmt17_rank', 'veri_rank', 'vehicleid_rank', 'veriwild_rank', 'sop_rank']

In [4]:
def get_df(train_data):
    ret = []
    for k, v in train_data.items():
        tmp = list(v['arch'])
        tmp1 = []
        for c in target_cols:
            tmp1.append(v[c])
        ret.append(tmp+tmp1+[k,v['arch']])
    retf = pd.DataFrame(ret,columns=[f'col{_}' for _ in range(len(tmp))]+target_cols+['id','arch'])
    retf['col0'] = retf['col0'].map({'l':1, 'j':2, 'k':3})
    int_cols = [x for x in retf.columns if x not in ['id','arch']]
    retf[int_cols] = retf[int_cols].astype(float)
    return retf

In [5]:
train_df = get_df(train_data)

In [6]:
from scipy.special import erfinv 

for c in target_cols:
    train_df[c+'_log1p'] = train_df[c].map(lambda x: np.log1p(x))
    train_y=train_df[c]
    mmin=np.min(train_y)+1
    mmax=np.max(train_y)+1
    train_y=np.sqrt(2) * erfinv(2 * (train_y+mmin)/(mmin+mmax)-1)
    train_df[c+'_trans_y'] = train_y

In [7]:
train_df.columns

Index(['col0', 'col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8',
       'col9', 'col10', 'col11', 'col12', 'col13', 'col14', 'col15', 'col16',
       'col17', 'col18', 'col19', 'col20', 'col21', 'col22', 'col23', 'col24',
       'col25', 'col26', 'col27', 'col28', 'col29', 'col30', 'col31', 'col32',
       'col33', 'col34', 'col35', 'col36', 'cplfw_rank', 'market1501_rank',
       'dukemtmc_rank', 'msmt17_rank', 'veri_rank', 'vehicleid_rank',
       'veriwild_rank', 'sop_rank', 'id', 'arch', 'cplfw_rank_log1p',
       'cplfw_rank_trans_y', 'market1501_rank_log1p',
       'market1501_rank_trans_y', 'dukemtmc_rank_log1p',
       'dukemtmc_rank_trans_y', 'msmt17_rank_log1p', 'msmt17_rank_trans_y',
       'veri_rank_log1p', 'veri_rank_trans_y', 'vehicleid_rank_log1p',
       'vehicleid_rank_trans_y', 'veriwild_rank_log1p',
       'veriwild_rank_trans_y', 'sop_rank_log1p', 'sop_rank_trans_y'],
      dtype='object')

In [8]:
train_df.iloc[:3]

col0  col1  col2  col3  col4  col5  col6  col7  col8  col9  ...  \
0   1.0   2.0   3.0   1.0   1.0   3.0   1.0   3.0   3.0   1.0  ...   
1   3.0   1.0   1.0   1.0   2.0   2.0   1.0   3.0   2.0   1.0  ...   
2   2.0   2.0   2.0   1.0   3.0   1.0   1.0   2.0   1.0   1.0  ...   

   msmt17_rank_log1p  msmt17_rank_trans_y  veri_rank_log1p  veri_rank_trans_y  \
0           6.073045             1.108919         5.793014           0.398015   
1           6.192362             1.978217         5.966147           0.766946   
2           5.411646            -0.132977         4.990433          -0.543441   

   vehicleid_rank_log1p  vehicleid_rank_trans_y  veriwild_rank_log1p  \
0              6.175867                1.751613             6.054439   
1              6.030685                0.955507             6.011267   
2              5.198497               -0.355046             4.615121   

   veriwild_rank_trans_y  sop_rank_log1p  sop_rank_trans_y  
0               1.037718        5.908083          0.626575  
1               0.894120        5.713733          0.265766  
2              -0.835931        3.555348         -1.476832  

[3 rows x 63 columns]

In [9]:
def get_step(train_df):
    res0 = []
    res1 = []
    res2 = []
    res3 = []
    res4 = []
    map_={'l':1, 'j':2, 'k':3}
    time_step=12
    for item in train_df.arch:
        ret = np.array(list(item[1:]),dtype=np.float32).reshape(-1,3)
        res0.append(ret[:,0][:time_step])
        res1.append(ret[:,1][:time_step])
        res2.append(ret[:,2][:time_step])
        res3.append(np.array([map_[item[0]]]*time_step))
        res4.append([map_[item[0]]]+list(np.array(list(item[1:]),dtype=np.float32)))
        
    train_df['head'] = res0
    train_df['mlp'] = res1
    train_df['emb'] = res2
    train_df['depth'] = res3
    train_df['all_emb'] = res4

In [10]:
#     retf['col0'] = retf['col0'].map({'j':10, 'k':11, 'l':12})
#     retf[num_heads] = retf[num_heads].replace({1:12, 2:11, 3:10})
#     retf[mlp_ratio] = retf[mlp_ratio].replace({1:4, 2:3.5, 3:3})
#     retf[emb_dim] = retf[emb_dim].replace({1:768})

In [11]:
def get_step(train_df):
    res0 = []
    res1 = []
    res2 = []
    res3 = []
    res4 = []
    map_={'l':1, 'j':2, 'k':3}
    time_step=12
    head_ = set([1+_*3 for _ in range(12)])
    mlp_ = set([2+_*3 for _ in range(12)])
    emb_ = set([3+_*3 for _ in range(12)])
    depth_ = set([0])
    for item in train_df.arch:
        ret = np.array(list(item[1:]),dtype=np.float32).reshape(-1,3)
        res0.append([1 if x in head_ else 0 for x in range(37)])
        res1.append([1 if x in mlp_ else 0 for x in range(37)])
        res2.append([1 if x in emb_ else 0 for x in range(37)])
        res3.append([1 if x in depth_ else 0 for x in range(37)])
        res4.append([map_[item[0]]]+list(np.array(list(item[1:]),dtype=np.float32)))
        
    train_df['head'] = res0
    train_df['mlp'] = res1
    train_df['emb'] = res2
    train_df['depth'] = res3
    train_df['all_emb'] = res4

In [12]:
get_step(train_df)

In [13]:
def get_step_0503(train_df):
    res0 = []
    res1 = []
    res2 = []
    res3 = []
    res4 = []
    map_={'l':1, 'j':2, 'k':3}
    time_step=12
    head_ = set([1+_*3 for _ in range(12)])
    mlp_ = set([2+_*3 for _ in range(12)])
    emb_ = set([3+_*3 for _ in range(12)])
    depth_ = set([0])
    for item in train_df.arch:
        ret = np.array(list(item[1:]),dtype=np.float32).reshape(-1,3)
        res0.append([int(item[x]) if x in head_ else 0 for x in range(37)])
        res1.append([int(item[x]) if x in mlp_ else 0 for x in range(37)])
        res2.append([int(item[x]) if x in emb_ else 0 for x in range(37)])
        res3.append([map_[item[0]]]+[0]*36)
        res4.append([map_[item[0]]]+list(np.array(list(item[1:]),dtype=np.float32)))
        
    train_df['head'] = res0
    train_df['mlp'] = res1
    train_df['emb'] = res2
    train_df['depth'] = res3
    train_df['all_emb'] = res4

In [14]:
#获取col级别的ohe映射
base_cols = [x for x in train_df.columns if x[:3]=='col']
print(f'base cols len: {len(base_cols)}')
cnt=0
emb_map={}
for i, c in enumerate(base_cols):
    nunique = sorted(train_df[c].unique())
    emb_map[i] = {}
    for v in nunique:
        emb_map[i][v]=cnt
        cnt+=1
emb_size = 0
for k, v in emb_map.items():
    emb_size += len(v)
print(f'embedding size: {emb_size}')

base cols len: 37
embedding size: 93


In [15]:
def all_emb_trans(x, emb_map):
    ret=[]
    for i, v in enumerate(x):
        ret.append(emb_map[i][v])
    return ret
    
def ohe_trans(train_df, emb_map):
    train_df['all_emb_vec'] = train_df['all_emb'].map(lambda x: all_emb_trans(x, emb_map))

In [16]:
ohe_trans(train_df, emb_map)

In [17]:
np.array(train_df['all_emb_vec'].tolist())

array([[ 0,  4,  8, ..., 86, 89, 92],
       [ 2,  3,  6, ..., 83, 87, 91],
       [ 1,  4,  7, ..., 83, 87, 91],
       ...,
       [ 0,  3,  6, ..., 85, 90, 92],
       [ 2,  3,  7, ..., 83, 87, 91],
       [ 0,  5,  7, ..., 86, 88, 92]])

In [18]:
from sklearn.model_selection import KFold
from tqdm import tqdm_notebook as tqdm

In [113]:
#定义数据
import torch
from torch.utils.data import Dataset

class MyDataset(Dataset):
    def __init__(self,df,use_cols,target_cols,show=0):
        self.df = df
        self.show = show
        self.use_cols = use_cols
        self.target_cols = target_cols

        self.prepare_data()
        
    def __len__(self):
        return self.df.shape[0]
    
    def prepare_data(self):
#         self.y = self.df[self.target_cols].values
        self.y = self.df[[x+'_trans_y' for x in self.target_cols]].values
        self.y0 = self.df[[self.target_cols[0]]].values
        self.y1 = self.df[[self.target_cols[1]]].values
        self.y2 = self.df[[self.target_cols[2]]].values
        self.y3 = self.df[[self.target_cols[3]]].values
        self.y4 = self.df[[self.target_cols[4]]].values
        self.y5 = self.df[[self.target_cols[5]]].values
        self.y6 = self.df[[self.target_cols[6]]].values
        self.y7 = self.df[[self.target_cols[7]]].values
        
        self.inputs = np.array(self.df['all_emb_vec'].tolist())
        
#         uc = ['all_emb_vec']
#         tmp_dt = {}
#         for c in uc:
#             tmp_dt[c] = np.array(self.df[c].tolist())
#         self.inputs = np.concatenate([tmp_dt[c][:, None] for c in uc], 1).transpose(0, 2, 1)


#         uc= ['all_emb','depth','head','mlp','emb']
#         tmp_dt = {}
#         for c in uc:
#             tmp_dt[c] = np.array(self.df[c].tolist())
#         self.inputs1= np.concatenate([tmp_dt[c][:, None] for c in uc], 1).transpose(0, 2, 1)
        
        
        if self.show==1:
            print('inputs_shape',self.inputs.shape)
#             print('inputs1_shape',self.inputs1.shape)
            print('y_shape',self.y.shape)
        
    def __getitem__(self, idx):
        data = {
            "input": F.one_hot(torch.tensor(self.inputs[idx]).long(), num_classes=emb_size).float(),
#             "input1": torch.tensor(self.inputs1[idx], dtype=torch.float),
            "y": torch.tensor(self.y[idx], dtype=torch.float),
#             "y_trans": torch.tensor(self.y[idx], dtype=torch.float),
            "y0": torch.tensor(self.y0[idx], dtype=torch.float),
            "y1": torch.tensor(self.y1[idx], dtype=torch.float),
            "y2": torch.tensor(self.y2[idx], dtype=torch.float),
            "y3": torch.tensor(self.y3[idx], dtype=torch.float),
            "y4": torch.tensor(self.y4[idx], dtype=torch.float),
            "y5": torch.tensor(self.y5[idx], dtype=torch.float),
            "y6": torch.tensor(self.y6[idx], dtype=torch.float),
            "y7": torch.tensor(self.y7[idx], dtype=torch.float),
        }
        
        return data

In [114]:
train_df.columns

Index(['col0', 'col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8',
       'col9', 'col10', 'col11', 'col12', 'col13', 'col14', 'col15', 'col16',
       'col17', 'col18', 'col19', 'col20', 'col21', 'col22', 'col23', 'col24',
       'col25', 'col26', 'col27', 'col28', 'col29', 'col30', 'col31', 'col32',
       'col33', 'col34', 'col35', 'col36', 'cplfw_rank', 'market1501_rank',
       'dukemtmc_rank', 'msmt17_rank', 'veri_rank', 'vehicleid_rank',
       'veriwild_rank', 'sop_rank', 'id', 'arch', 'cplfw_rank_log1p',
       'cplfw_rank_trans_y', 'market1501_rank_log1p',
       'market1501_rank_trans_y', 'dukemtmc_rank_log1p',
       'dukemtmc_rank_trans_y', 'msmt17_rank_log1p', 'msmt17_rank_trans_y',
       'veri_rank_log1p', 'veri_rank_trans_y', 'vehicleid_rank_log1p',
       'vehicleid_rank_trans_y', 'veriwild_rank_log1p',
       'veriwild_rank_trans_y', 'sop_rank_log1p', 'sop_rank_trans_y', 'head',
       'mlp', 'emb', 'depth', 'all_emb', 'all_emb_vec'],
      dtype='object'

In [115]:
train0 = train_df.sample(400, random_state=666).reset_index(drop=True)
val0 = train_df[~train_df.id.isin(train0.id)].reset_index(drop=True)

In [116]:
use_cols = [x for x in train_df.columns if 'col' in x]

In [117]:
len(use_cols)

37

In [118]:
train_dataset = MyDataset(train0, use_cols, target_cols, 1)
val_dataset = MyDataset(val0, use_cols, target_cols, 1)

inputs_shape (400, 37)
y_shape (400, 8)
inputs_shape (100, 37)
y_shape (100, 8)


In [119]:
import os
import torch.nn.functional as F
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

In [120]:
train_dataset[:3]['input']

tensor([[[0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 1., 0.]],

        [[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 1., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 1.]],

        [[0., 0., 1.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 1., 0.]]])

In [121]:
import gc
import os
import time
import random
import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader
from transformers import get_linear_schedule_with_warmup


def seed_everything(seed):
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    
    
def count_parameters(model, all=False):
    if all:
        return sum(p.numel() for p in model.parameters())
    else:
        return sum(p.numel() for p in model.parameters() if p.requires_grad)


def save_model_weights(model, modelpath, filename):
    torch.save(model.state_dict(), modelpath+filename)
    return f"\n -> Save weights to {modelpath+filename}\n"

In [122]:
import scipy

In [240]:
def compute_metric(pred, y):
    corr = []
    if pred.shape[1]>2:
        for i in range(8):
            corr.append(scipy.stats.stats.kendalltau(pred[:, i], y[:, i])[0])
    else:
        corr.append(scipy.stats.stats.kendalltau(pred, y)[0])
    return np.array(corr)

class CVPRLoss(nn.Module):
    def __call__(self, pred, y):
        pred_mean, y_mean = pred.mean(0), y.mean(0)
        pred_std, y_std = pred.std(0), y.std(0)
        corr = ((pred - pred_mean) * (y - y_mean)).sum(0) / ((((pred - pred_mean)**2).sum(0).sqrt()) * (((y - y_mean)**2).sum(0).sqrt())) 
    
#         cos = nn.CosineSimilarity(dim=0, eps=1e-08)
#         corr1 = cos(pred, y)
#         corr2 = (corr+corr1)/2
        return 1-corr

from fast_soft_sort.pytorch_ops import soft_rank
class CVPRLoss1(nn.Module):
    #spearman
    def __call__(self, pred, y):
        pred = pred.cpu()
        y = y.cpu()
        return 1-torch.cat(
            [self.spearman(y[:,i].reshape(1,-1), 
                           pred[:,i].reshape(1,-1)).reshape(1,1) for i in range(y.shape[1])]
        ).reshape(1, -1)
        
    def corrcoef(self, target, pred):
        # np.corrcoef in torch from @mdo
        # https://forum.numer.ai/t/custom-loss-functions-for-xgboost-using-pytorch/960
        pred_n = pred - pred.mean()
        target_n = target - target.mean()
        pred_n = pred_n / pred_n.norm()
        target_n = target_n / target_n.norm()
        return (pred_n * target_n).sum()


    def spearman(self,
        target,
        pred,
        regularization="l2",
        regularization_strength=0.01,
    ):
        # fast_soft_sort uses 1-based indexing, divide by len to compute percentage of rank
        pred = soft_rank(
            pred,
            regularization=regularization,
            regularization_strength=regularization_strength,
        )
    #     print(pred)
        return self.corrcoef(target, pred / pred.shape[-1])
     
class CVPRLoss2(nn.Module):
    #kendall soft rank+tanh
    def __call__(self, pred, y):
        pred = pred.cpu()
        y = y.cpu()
        return 1-torch.cat(
            [self.get_score(y[:,i].reshape(1,-1), 
                           pred[:,i].reshape(1,-1)).reshape(1,-1) for i in range(y.shape[1])]
        ).reshape(1, -1)
        
    def get_score(self, actuals, preds):
        sa = actuals.argsort()[0]

        tmp = soft_rank(
            preds.index_select(1, sa),
            regularization='l2',
            regularization_strength=0.01,
        )[0]-1
        
        tmp = tmp.cuda()

        score = torch.cat([((tmp[i:]-tmp[i-1]) * 10).tanh() for i in range(1, tmp.shape[0])]).sum()
        score1 = score/sum(list(range(1,len(tmp))))
        return score1
    
class CVPRLoss_softrank(nn.Module):
    #kendall soft rank+tanh
    def __call__(self, pred, y):
        pred = pred.cpu()
        y = y.cpu()
        return 1-torch.cat(
            [self.get_score(y[:,i].reshape(1,-1), 
                           pred[:,i].reshape(1,-1)).reshape(1,-1) for i in range(y.shape[1])]
        ).reshape(1, -1)
        
    def get_score(self, actuals, preds):
        sa = actuals.argsort()[0]

        tmp = soft_rank(
            preds.index_select(1, sa),
            regularization='l2',
            regularization_strength=0.01,
        )[0]-1
        
        tmp = tmp.cuda()

        score = torch.cat([((tmp[i:]-tmp[i-1]) * 10).tanh() for i in range(1, tmp.shape[0])]).sum()
        score1 = score/sum(list(range(1,len(tmp))))
        return score1
    
class CVPRLoss_softsign(nn.Module):
    #kendall softsign
    def __call__(self, pred, y):
        return 1-torch.cat(
            [self.get_score(y[:,i].reshape(1,-1), 
                           pred[:,i].reshape(1,-1)).reshape(1,-1) for i in range(y.shape[1])]
        ).reshape(1, -1)

    
    def get_score(self, actuals, preds):
        sa = actuals.argsort()[0]
        tmp = preds.index_select(1, sa.int())[0]
        score = torch.cat([(tmp[i:]-tmp[i-1])/(0.01+torch.abs(tmp[i:]-tmp[i-1])) for i in range(1, tmp.shape[0])]).sum()
        score1 = score/sum(list(range(1,len(tmp))))
        return score1
    
class CVPRLoss_tanh(nn.Module):
    # kendall tanh
    def __call__(self, pred, y):
        return 1-torch.cat(
            [self.get_score(y[:,i].reshape(1,-1), 
                           pred[:,i].reshape(1,-1)).reshape(1,-1) for i in range(y.shape[1])]
        ).reshape(1, -1)
    
    def get_score(self, actuals, preds):
        sa = actuals.argsort()[0]
        tmp = preds.index_select(1, sa.int())[0]
        score = torch.cat([((tmp[i:]-tmp[i-1])).tanh() for i in range(1, tmp.shape[0])]).sum()
        score1 = score/sum(list(range(1,len(tmp))))
        return score1
    
    
class CVPRLoss_pair(nn.Module):
    def __call__(self, pred, y):
        return torch.cat(
            [self.pair_loss(pred[:,i], y[:,i]).reshape(1) for i in range(y.shape[1])]
        ).reshape(1,-1)
    
    def pair_loss(self, outputs, labels):
        output = outputs.unsqueeze(1)
        output1 = output.repeat(1,outputs.shape[0])
        label = labels.unsqueeze(1)
        label1 = label.repeat(1,labels.shape[0])

        tmp = (output1-output1.t())*torch.sign(label1-label1.t())
        tmp = torch.log(1+torch.exp(-tmp))
        eye_tmp = tmp*torch.eye(len(tmp)).cuda()
        new_tmp = tmp - eye_tmp
        loss = torch.sum(new_tmp)/(outputs.shape[0]*(outputs.shape[0]-1))

        return loss
    
class CVPRLoss_tanh1(nn.Module):
    # kendall tanh
    def __call__(self, pred, y):
        return 1-torch.cat(
            [self.get_score(pred[:,i], y[:,i]).reshape(1) for i in range(y.shape[1])]
        ).reshape(1,-1)
    
    def get_score(self, outputs, labels):
        output1 = outputs.unsqueeze(1).repeat(1,outputs.shape[0])
        label1 = labels.unsqueeze(1).repeat(1,labels.shape[0])

        tmp = ((output1-output1.t())*torch.sign(label1-label1.t())).tanh()
        eye_tmp = tmp*torch.eye(tmp.shape[0]).cuda()
        new_tmp = tmp - eye_tmp
        
        loss = torch.sum(new_tmp)/(outputs.shape[0]*(outputs.shape[0]-1))

        return loss

In [259]:
a = torch.rand(10,8)
b = torch.rand(10,8)

In [263]:
a

tensor([[0.2938, 0.2423, 0.7752, 0.0256, 0.1991, 0.9268, 0.0134, 0.4208],
        [0.6928, 0.4624, 0.2987, 0.3412, 0.1029, 0.0951, 0.0813, 0.6073],
        [0.7384, 0.9386, 0.9592, 0.0099, 0.2762, 0.9415, 0.9735, 0.2123],
        [0.4335, 0.7689, 0.7141, 0.6306, 0.9647, 0.6990, 0.2901, 0.8998],
        [0.7991, 0.8953, 0.9382, 0.5447, 0.4371, 0.3246, 0.6299, 0.1848],
        [0.8725, 0.5740, 0.6805, 0.2139, 0.8551, 0.4425, 0.3220, 0.5634],
        [0.9424, 0.1038, 0.3128, 0.9155, 0.1701, 0.4086, 0.1180, 0.0268],
        [0.4690, 0.5625, 0.6190, 0.5634, 0.2022, 0.9743, 0.8215, 0.7969],
        [0.3751, 0.8123, 0.4700, 0.1645, 0.0775, 0.7283, 0.9384, 0.5328],
        [0.8556, 0.8728, 0.7289, 0.7389, 0.8056, 0.3314, 0.1437, 0.3971]])

In [264]:
b

tensor([[0.7886, 0.7386, 0.6597, 0.2135, 0.8904, 0.2576, 0.5863, 0.9053],
        [0.9750, 0.5364, 0.0218, 0.8977, 0.9828, 0.5364, 0.4371, 0.9436],
        [0.2283, 0.6415, 0.6987, 0.8738, 0.3110, 0.4822, 0.2738, 0.2551],
        [0.2761, 0.3374, 0.1084, 0.9647, 0.6921, 0.8249, 0.4304, 0.2376],
        [0.1829, 0.0712, 0.9496, 0.6148, 0.5417, 0.6939, 0.6082, 0.3026],
        [0.2022, 0.3713, 0.7872, 0.2586, 0.4004, 0.5719, 0.5471, 0.3807],
        [0.4728, 0.3330, 0.7842, 0.4638, 0.5625, 0.0845, 0.6487, 0.7132],
        [0.3503, 0.6804, 0.7270, 0.3791, 0.6012, 0.0648, 0.1171, 0.0075],
        [0.5199, 0.0925, 0.0760, 0.2101, 0.7753, 0.2312, 0.1764, 0.7262],
        [0.7131, 0.3528, 0.6152, 0.0677, 0.3141, 0.8574, 0.3529, 0.7444]])

In [260]:
loss0 = CVPRLoss_tanh()
loss1 = CVPRLoss_tanh1()

In [261]:
loss0(a,b).float()

tensor([[1.0851, 1.0981, 0.8938, 0.9677, 1.1583, 1.1568, 1.2418, 1.0679]])

In [262]:
loss1(a,b)

tensor([[1.0851, 1.0981, 0.8938, 0.9677, 1.1583, 1.1568, 1.2418, 1.0679]])

In [124]:
train_dataset[:]['y']

tensor([[ 1.3669, -0.1380,  0.7941,  ..., -0.0175,  0.4473, -0.2348],
        [-0.2091,  1.2067,  0.9634,  ...,  0.6084,  1.2492,  1.7070],
        [-1.2067, -0.9398,  0.1836,  ...,  1.1467, -0.3872, -0.6698],
        ...,
        [ 0.2348, -0.9634, -1.5903,  ...,  0.5904, -0.7404, -1.6458],
        [-0.7536,  0.1735,  1.2714,  ...,  0.9398,  0.1330, -0.1481],
        [-0.6327, -0.6205, -0.7872,  ...,  1.9782, -0.3232, -0.4695]])

In [187]:
def train(model, 
        train_dataset, 
        val_dataset, 
        verbose=20, 
        fold_=0,
        modelname='MLP_base',
        modelpath=r'./model'+'//',
        input='input',
        y='y',
        early_stop_round=60,
        debug=False):
    
    print(f'Model parameters count: {count_parameters(model)}')
    #数据加载
    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        drop_last=True,
        pin_memory=True
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=BATCH_SIZE_TEST,
        shuffle=False,
        drop_last=False,
        pin_memory=True
    )
    print(f'train batch num: {len(train_loader)}')
    print(f'val batch num: {len(val_loader)}')
            
    # Optimizer
    optimizer = getattr(torch.optim, optim)(model.parameters(), lr=LR)
    # Scheduler
    num_warmup_steps = int(0.1 * EPOCHS * len(train_loader))
    num_training_steps = int(EPOCHS * len(train_loader))
    scheduler = get_linear_schedule_with_warmup(
        optimizer, num_warmup_steps, num_training_steps
    )
    print(f'optim: {optim}, lr: {LR}, warmup_steps: {num_warmup_steps}')
    
    
    #train
    bst_epoch=0
    score_best=0
    first_epoch_eval=0
    for epoch in range(EPOCHS):
        if epoch > early_stop_round and (epoch - bst_epoch > early_stop_round):
            print(f'early stopping.')
            break
            
        model.train()
        model.zero_grad()
        start_time = time.time()

        avg_loss = 0
        for data in train_loader:
            pred = model(data[input].to(device))

            loss = loss_fct(
                pred,
                data[y].to(device)
            ).mean()

            loss.backward()
            avg_loss += loss.item() / len(train_loader)

            optimizer.step()
            scheduler.step()

            optimizer.zero_grad(set_to_none=True)

        #VAL
        model.eval()
        mae, avg_val_loss = 0, 0
        preds = []

        with torch.no_grad():
            for data in val_loader:
                pred = model(data[input].to(device))

                loss = loss_fct(
                    pred,
                    data[y].to(device)
                ).mean()

                avg_val_loss += loss.item() / len(val_loader)

                preds.append(pred.detach().cpu().numpy())

        preds = np.concatenate(preds, 0)
        if y=='y':
            mae = compute_metric(preds,val_dataset.df[target_cols].values).mean()
        else:
            mae = compute_metric(preds,val_dataset.df[[target_cols[int(y.replace('y',''))]]].values).mean()
        
        elapsed_time = time.time() - start_time
        if (epoch + 1) % verbose == 0:
            elapsed_time = elapsed_time * verbose
            lr = scheduler.get_last_lr()[0]
    #         lr=LR
            print(
                f"Epoch {epoch + 1:02d}/{ EPOCHS:02d} \t lr={lr:.1e}\t t={elapsed_time:.0f}s \t"
                f"loss={avg_loss:.4f}",
                end="\t",
            )

            if (epoch + 1 >= first_epoch_eval) or (epoch + 1 == EPOCHS):
                print(f"val_loss={avg_val_loss:.4f}\tcorr={mae:.4f}")
            else:
                print("")
                
        #保存最优模型
        if mae>score_best:
            bst = save_model_weights(model, modelpath, f'{modelname}_{fold_}.pt')
            score_best = mae
            bst_epoch = epoch
            if y=='y':
                bst_list = compute_metric(preds,val_dataset.df[target_cols].values)
            else:
                bst_list = compute_metric(preds,val_dataset.df[[target_cols[int(y.replace('y',''))]]].values).mean()
            bst_preds = preds
    print(f'best score {score_best}, best epoch: {bst_epoch}, {bst} ' )
    print(bst_list,'\n\n')
    del (val_loader, train_loader, loss, data, pred)
    gc.collect()
    torch.cuda.empty_cache()
    
    return bst_preds, bst_list

In [188]:
class CVPRModel(nn.Module):
    def __init__(
        self,
        input_dim=3,
        num_classes=8,
        time_step=12,
        bi=True
    ):
        super(CVPRModel,self).__init__()
        
        self.bi_num = 2 if bi else 1
        self.time_step = time_step
        
        self.MLP = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 256),
            nn.ReLU(),
            nn.Linear(256, 256),
            nn.ReLU(),
        )
        
        self.LSTM0 = nn.LSTM(256, 256, 
                    batch_first=True, 
                    bidirectional=bi, 
                    num_layers=1,
                    dropout=0)
                                 
        
        self.LSTM1 = nn.LSTM(512, 256, 
                    batch_first=True, 
                    bidirectional=bi, 
                    num_layers=1,
                    dropout=0
                            )    
        
        self.Logits0 = nn.Sequential(
            nn.Flatten(start_dim=1),
            nn.Linear((93)*self.time_step, 256),
            nn.ReLU(),
        
        )
        
        self.Logits1 = nn.Sequential(
            nn.Flatten(start_dim=1),
            nn.Linear((256)*self.time_step, 512),
            nn.ReLU(),
            nn.Linear(512, 256),
            nn.ReLU(),
        )
        
        self.Logits2 = nn.Sequential(
            nn.Flatten(start_dim=1),
            nn.Linear((512)*self.time_step, 1024),
            nn.ReLU(),
            nn.Linear(1024, 256),
            nn.ReLU(),
        )
        
        self.Logits3 = nn.Sequential(
            nn.Flatten(start_dim=1),
            nn.Linear((512)*self.time_step, 1024),
            nn.ReLU(),
            nn.Linear(1024, 256),
            nn.ReLU(),
        )
        
        
        self.fc = nn.Sequential(
            nn.Linear(4, 1),
            nn.Flatten(start_dim=1),
            nn.Linear(256, num_classes)
        )
        
    def forward(self, x):
        x1 = self.MLP(x)
        x2, (h0, c0) = self.LSTM0(x1)
        x3, (h1, c1) = self.LSTM1(x2, (h0, c0))
        
        p0 = self.Logits0(x)
        p1 = self.Logits1(x1)
        p2 = self.Logits2(x2)
        p3 = self.Logits3(x3)


        c1 = torch.cat([
            p0.unsqueeze(2), 
            p1.unsqueeze(2), 
            p2.unsqueeze(2), 
            p3.unsqueeze(2), 
                       ],-1
        )
        
        pred = self.fc(c1)
        
        return pred

In [189]:
#参数设置
seed = 666
BATCH_SIZE = 400
BATCH_SIZE_TEST = 128
EPOCHS = 300
LR = 0.001
optim = "Adam"
device = "cuda" if torch.cuda.is_available() else "cpu"
modelpath = r'./model'+'//'

In [190]:
a = torch.rand(128,37,93).to(device)
net = CVPRModel(input_dim=93,
                num_classes=len(target_cols),
                bi=True,
                time_step=37
               ).to(device)
b = net(a)
b.shape

torch.Size([128, 8])

In [191]:
b[1].shape

torch.Size([8])

In [192]:
b.flatten(1).shape

torch.Size([128, 8])

In [193]:
del a,b,net;
gc.collect()
torch.cuda.empty_cache()

In [194]:
class CVPRLoss_tanh1(nn.Module):
    # kendall tanh
    def __call__(self, pred, y):
        return 1-torch.cat(
            [self.get_score(pred[:,i], y[:,i]).reshape(1) for i in range(y.shape[1])]
        ).reshape(1,-1)
    
    def get_score(self, outputs, labels):
        output1 = outputs.unsqueeze(1).repeat(1,outputs.shape[0])
        label1 = labels.unsqueeze(1).repeat(1,labels.shape[0])

        tmp = ((output1-output1.t())*torch.sign(label1-label1.t())).tanh()
        eye_tmp = tmp*torch.eye(tmp.shape[0]).cuda()
        new_tmp = tmp - eye_tmp
        
        loss = torch.sum(new_tmp)/(outputs.shape[0]*(outputs.shape[0]-1))

        return loss

In [196]:
#参数设置
seed = 666
BATCH_SIZE = 400
BATCH_SIZE_TEST = 128
EPOCHS = 300
LR = 0.001
optim = "Adam"
device = "cuda" if torch.cuda.is_available() else "cpu"
modelpath = r'E:\cvpr_model'+'//'

# loss_fct = CVPRLoss_tanh()
loss_fct = CVPRLoss_tanh1()
# loss_fct = nn.MSELoss()
index = '_t'
seed_everything(seed)
modelname = 'LSTM1_step37_base1_test'
model = CVPRModel(input_dim=93,
                num_classes=8,
                bi=True,
                time_step=37
               ).to(device)
preds,_ = train(model, 
            train_dataset, 
            val_dataset, 
            verbose=20, 
            fold_=index,
            modelname=modelname,
            modelpath=modelpath,
            input='input',
            y='y',
            debug=False
             )

Model parameters count: 47929357
train batch num: 1
val batch num: 1
optim: Adam, lr: 0.001, warmup_steps: 30
Epoch 20/300 	 lr=6.7e-04	 t=4s 	loss=0.9480	val_loss=0.9393	corr=0.5272
Epoch 40/300 	 lr=9.6e-04	 t=4s 	loss=0.4272	val_loss=0.4541	corr=0.5595
Epoch 60/300 	 lr=8.9e-04	 t=4s 	loss=0.2842	val_loss=0.3034	corr=0.7079
Epoch 80/300 	 lr=8.1e-04	 t=4s 	loss=0.2290	val_loss=0.2573	corr=0.7482
Epoch 100/300 	 lr=7.4e-04	 t=4s 	loss=0.1961	val_loss=0.2264	corr=0.7783
Epoch 120/300 	 lr=6.7e-04	 t=3s 	loss=0.1801	val_loss=0.2097	corr=0.7942
Epoch 140/300 	 lr=5.9e-04	 t=3s 	loss=0.1680	val_loss=0.2133	corr=0.7870
Epoch 160/300 	 lr=5.2e-04	 t=4s 	loss=0.1527	val_loss=0.2296	corr=0.7726
Epoch 180/300 	 lr=4.4e-04	 t=4s 	loss=0.1325	val_loss=0.2246	corr=0.7774
early stopping.
best score 0.7942424242424243, best epoch: 119, 
 -> Save weights to E:\cvpr_model//LSTM1_step37_base1_test__t.pt
 
[0.3430303  0.87676768 0.88767677 0.95676768 0.88444444 0.66787879
 0.91676768 0.82060606] 




In [197]:
# [0.3430303  0.87676768 0.88767677 0.95676768 0.88444444 0.66787879 0.91676768 0.82060606] 
# [0.33494949 0.87111111 0.89333333 0.96040404 0.88242424 0.65616162 0.91717172 0.81414141] 
# [0.25979798 0.84808081 0.91191919 0.9620202  0.90585859 0.68767677 0.93171717 0.78585859] 

In [198]:
# 0.7689898989898991 [0.27191919 0.85818182 0.88080808 0.93616162 0.85575758 0.6759596 0.86949495 0.80363636] 

In [199]:
# 2层自带lstm 0.7911616161616162 
# 1层的输出作为2层的h和c 0.7920707070707071
# 2层手写，不初始化 0.7911616161616162 
# 3层手写，输出作为输入 0.7911111111111113 
# 2自带*2自带，输出作为输入 0.7875757575757577 
# 1层输出作为2层输入，最后2层输出cat 0.7894444444444446
# 1层输出作为2层输入，最后2层输出相乘 0.7885858585858587
# 1层的输出作为2层的h和c,加一层gru cat 0.7894949494949497 
# 1层的输出作为2层的h和c,加一层gru*1层输出 cat 0.7886868686868689
# 1层的输出作为2层的h和c,加2层gru cat 0.7913131313131314 
# 1层的输出作为2层的h和c,加2层gru*1层输出 cat2层输出 0.7915151515151516 
# 1层的输出作为2层的h和c，2层的输出transformer然后乘以2层的输出，0.7899494949494951
# 1层的输出作为2层的h和c,Tanh 0.7893939393939395 
# 1层的输出作为2层的h和c,relu 0.7862121212121214 
# 1层的输出作为2层的h和c,fc出去，0.7872222222222224 

In [200]:
# index = '_t'
# modelname = 'LSTM1_step37_base1_test'
# scoref = []
# for i in range(8):
#     seed_everything(seed)
#     model = CVPRModel(input_dim=1,
#                     num_classes=1,
#                     bi=True,
#                     time_step=37
#                    ).to(device)
#     preds,_ = train(model, 
#                 train_dataset, 
#                 val_dataset, 
#                 verbose=20, 
#                 fold_=index,
#                 modelname=modelname,
#                 modelpath=modelpath,
#                 input='input',
#                 y=f'y{i}',
#                 debug=False
#                  )
#     scoref.append(_)
# np.mean(scoref)

In [201]:
# [0.33171717 0.86222222 0.88888889 0.94222222 0.8630303  0.66909091 0.9030303  0.79757576]

In [202]:
# a = torch.arange(-50,50,0.1)
# b = a.tanh()
# df = pd.DataFrame()
# df['a'] = a.detach().numpy()
# df['b'] = a.tanh()
# df['b0'] = (a*2).tanh()
# df['b1'] = (a*0.1).tanh()
# df.plot(x='a',y=['b','b0','b1'])

In [206]:
def train_sig(model, 
        train_dataset, 
        val_dataset, 
        verbose=20, 
        fold_=0,
        modelname='MLP_base',
        modelpath=r'./model'+'//',
        input='input',
        y='y',
        early_stop_round=60,
        debug=False):
    
    print(f'Model parameters count: {count_parameters(model)}')
    #数据加载
    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        drop_last=True,
        pin_memory=True
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=BATCH_SIZE_TEST,
        shuffle=False,
        drop_last=False,
        pin_memory=True
    )
    print(f'train batch num: {len(train_loader)}')
    print(f'val batch num: {len(val_loader)}')
            
    # Optimizer
    optimizer = getattr(torch.optim, optim)(model.parameters(), lr=LR)
    # Scheduler
    num_warmup_steps = int(0.1 * EPOCHS * len(train_loader))
    num_training_steps = int(EPOCHS * len(train_loader))
    scheduler = get_linear_schedule_with_warmup(
        optimizer, num_warmup_steps, num_training_steps
    )
    print(f'optim: {optim}, lr: {LR}, warmup_steps: {num_warmup_steps}')
    
    
    #train
    bst_epoch={_:0 for _ in range(8)}
    score_best={_:0 for _ in range(8)}
    first_epoch_eval=0
    for epoch in range(EPOCHS):
        
        model.train()
        model.zero_grad()
        start_time = time.time()

        avg_loss = 0
        for data in train_loader:
            pred = model(data[input].to(device))
#             print(pred.shape,data['y'].shape)

            loss = loss_fct(
                pred,
                data[y].to(device)
            ).mean()

            loss.backward()
            avg_loss += loss.item() / len(train_loader)

            optimizer.step()
            scheduler.step()

            optimizer.zero_grad(set_to_none=True)

        #VAL
        model.eval()
        mae, avg_val_loss = 0, 0
        preds = []

        with torch.no_grad():
            for data in val_loader:
                pred = model(data[input].to(device))

                loss = loss_fct(
                    pred,
                    data[y].to(device)
                ).mean()

                avg_val_loss += loss.item() / len(val_loader)

                preds.append(pred.detach().cpu().numpy())

        preds = np.concatenate(preds, 0)
        if y=='y':
            mae = compute_metric(preds,val_dataset.df[target_cols].values).mean()
        else:
            mae = compute_metric(preds,val_dataset.df[[target_cols[int(y.replace('y',''))]]].values).mean()
        
        elapsed_time = time.time() - start_time
        if (epoch + 1) % verbose == 0:
            elapsed_time = elapsed_time * verbose
            lr = scheduler.get_last_lr()[0]
    #         lr=LR
            print(
                f"Epoch {epoch + 1:02d}/{ EPOCHS:02d} \t lr={lr:.1e}\t t={elapsed_time:.0f}s \t"
                f"loss={avg_loss:.4f}",
                end="\t",
            )

            if (epoch + 1 >= first_epoch_eval) or (epoch + 1 == EPOCHS):
                print(f"val_loss={avg_val_loss:.4f}\tcorr={mae:.4f}")
            else:
                print("")
                
        #保存最优模型
        score1 = compute_metric(preds,val_dataset.df[target_cols].values)
        for i in range(8):
            if score1[i] > score_best[i]:
                bst = save_model_weights(model, modelpath, f'{modelname}_target{i}_{fold_}.pt')
                score_best[i] = score1[i]
                bst_epoch[i] = epoch
#                 print(f'target{i} best score {score_best[i]}, best epoch: {bst_epoch[i]}, {bst} ' )
                
    bst_list = [score_best[i] for i in range(8)]
    print(bst_list,'\n\n')
    del (val_loader, train_loader, loss, data, pred)
    gc.collect()
    torch.cuda.empty_cache()
    
    return bst_list


In [207]:
# K折训练，同时
seed = 666
BATCH_SIZE = 400
BATCH_SIZE_TEST = 128
EPOCHS = 300
LR = 0.001
optim = "Adam"
device = "cuda" if torch.cuda.is_available() else "cpu"
modelpath = r'E:\cvpr_model'+'//'

In [208]:
loss_fct = CVPRLoss_tanh1()
# loss_fct = CVPRLoss_pair()
k=5
scoref = []
skf = KFold(n_splits=k, shuffle=False)
for index, (train_index, test_index) in enumerate(skf.split(train_df)):   
    print(f'FOLD {index}')
    train0 = train_df.iloc[train_index]
    val0 = train_df.iloc[test_index]   
    train_dataset = MyDataset(train0, use_cols, target_cols)
    val_dataset = MyDataset(val0, use_cols, target_cols)
    print(f'train size: {len(train0)}, val size: {len(val0)}')

    modelname = f'lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe'
    seed_everything(seed)
    model = CVPRModel(input_dim=93,
                    num_classes=8,
                    bi=True,
                    time_step=37
                   ).to(device)

    _ = train_sig(model, 
                train_dataset, 
                val_dataset, 
                verbose=10, 
                fold_=index,
                modelname=modelname,
                modelpath=modelpath,
                input='input',
                y='y',
                debug=False
                 )
    scoref.append(_)
scoreff = scoref
print(np.round(np.array(scoreff).mean(1).mean(), 5), [round(x, 5) for x in np.array(scoreff).mean(0)])

FOLD 0
train size: 400, val size: 100
Model parameters count: 47929357
train batch num: 1
val batch num: 1
optim: Adam, lr: 0.001, warmup_steps: 30
Epoch 10/300 	 lr=3.3e-04	 t=3s 	loss=0.9944	val_loss=0.9941	corr=0.3516
Epoch 20/300 	 lr=6.7e-04	 t=3s 	loss=0.9461	val_loss=0.9386	corr=0.4895
Epoch 30/300 	 lr=1.0e-03	 t=2s 	loss=0.5329	val_loss=0.5487	corr=0.4619
Epoch 40/300 	 lr=9.6e-04	 t=3s 	loss=0.4277	val_loss=0.4784	corr=0.5292
Epoch 50/300 	 lr=9.3e-04	 t=2s 	loss=0.3558	val_loss=0.3806	corr=0.6351
Epoch 60/300 	 lr=8.9e-04	 t=2s 	loss=0.2947	val_loss=0.3149	corr=0.6967
Epoch 70/300 	 lr=8.5e-04	 t=3s 	loss=0.2561	val_loss=0.2833	corr=0.7261
Epoch 80/300 	 lr=8.1e-04	 t=2s 	loss=0.2305	val_loss=0.2556	corr=0.7525
Epoch 90/300 	 lr=7.8e-04	 t=2s 	loss=0.2083	val_loss=0.2341	corr=0.7709
Epoch 100/300 	 lr=7.4e-04	 t=2s 	loss=0.1941	val_loss=0.2224	corr=0.7822
Epoch 110/300 	 lr=7.0e-04	 t=2s 	loss=0.1848	val_loss=0.2206	corr=0.7833
Epoch 120/300 	 lr=6.7e-04	 t=2s 	loss=0.1777	v

In [210]:
# 0.79236 [0.31685, 0.87071, 0.90166, 0.96186, 0.89802, 0.67467, 0.91814, 0.79701]

In [211]:
# 0.7 0.77966 [0.26691, 0.86489, 0.8943, 0.96145, 0.89042, 0.65576, 0.912, 0.79152]
(0.7803, [0.26618, 0.86804, 0.89471, 0.95782, 0.89059, 0.66764, 0.90909, 0.78836])

(0.7803,
 [0.26618, 0.86804, 0.89471, 0.95782, 0.89059, 0.66764, 0.90909, 0.78836])

In [212]:
# loss_fct = CVPRLoss_softsign()
# k=5
# scoref = []
# skf = KFold(n_splits=k, shuffle=False)
# for index, (train_index, test_index) in enumerate(skf.split(train_df)):   
#     print(f'FOLD {index}')
#     train0 = train_df.iloc[train_index]
#     val0 = train_df.iloc[test_index]   
#     train_dataset = MyDataset(train0, use_cols, target_cols)
#     val_dataset = MyDataset(val0, use_cols, target_cols)
#     print(f'train size: {len(train0)}, val size: {len(val0)}')

#     modelname = f'LSTM_2layer_step37_kendall_8all_softsign'
#     seed_everything(seed)
#     model = CVPRModel(input_dim=1,
#                     num_classes=8,
#                     bi=True,
#                     time_step=37
#                    ).to(device)
#     preds,_ = train(model, 
#                 train_dataset, 
#                 val_dataset, 
#                 verbose=100, 
#                 fold_=index,
#                 modelname=modelname,
#                 modelpath=modelpath,
#                 input='input',
#                 y='y',
#                 debug=False
#                  )
#     scoref.append(_)
# scoreff = scoref
# np.round(np.array(scoreff).mean(1).mean(), 5), [round(x, 5) for x in np.array(scoreff).mean(0)]

In [213]:
np.round(np.array(scoreff).mean(1).mean(), 5), [round(x, 5) for x in np.array(scoreff).mean(0)]

(0.79286,
 [0.3078, 0.87152, 0.90384, 0.96145, 0.90044, 0.67943, 0.91846, 0.79992])

In [214]:
# (0.78795,
#  [0.26836, 0.87111, 0.90545, 0.96509, 0.89745, 0.67507, 0.91895, 0.8021])

In [215]:
#加载test
with open('./data/CVPR_2022_NAS_Track2_test.json', 'r') as f:
    test_data = json.load(f)
test_data['arch99997']

{'cplfw_rank': 0,
 'market1501_rank': 0,
 'dukemtmc_rank': 0,
 'msmt17_rank': 0,
 'veri_rank': 0,
 'vehicleid_rank': 0,
 'veriwild_rank': 0,
 'sop_rank': 0,
 'arch': 'j121221121221221311331321121221000000'}

In [216]:
test_df = get_df(test_data)
get_step(test_df)

In [217]:
ohe_trans(test_df, emb_map)

In [218]:
test_df.iloc[:3]

col0  col1  col2  col3  col4  col5  col6  col7  col8  col9  ...  \
0   3.0   2.0   3.0   1.0   1.0   3.0   1.0   2.0   1.0   1.0  ...   
1   1.0   1.0   1.0   1.0   2.0   1.0   1.0   2.0   1.0   1.0  ...   
2   2.0   2.0   1.0   1.0   3.0   2.0   1.0   1.0   3.0   1.0  ...   

   veriwild_rank  sop_rank       id                                   arch  \
0            0.0       0.0  arch501  k231131211331131121131121311111211000   
1            0.0       0.0  arch502  l111211211121121111331311221211121111   
2            0.0       0.0  arch503  j211321131221321331211131321131000000   

                                                head  \
0  [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, ...   
1  [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, ...   
2  [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, ...   

                                                 mlp  \
0  [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, ...   
1  [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, ...   
2  [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, ...   

                                                 emb  \
0  [0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, ...   
1  [0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, ...   
2  [0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, ...   

                                               depth  \
0  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                             all_emb  \
0  [3, 2.0, 3.0, 1.0, 1.0, 3.0, 1.0, 2.0, 1.0, 1....   
1  [1, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1....   
2  [2, 2.0, 1.0, 1.0, 3.0, 2.0, 1.0, 1.0, 3.0, 1....   

                                         all_emb_vec  
0  [2, 4, 8, 9, 10, 15, 16, 18, 20, 23, 26, 29, 3...  
1  [0, 3, 6, 9, 11, 13, 16, 18, 20, 23, 24, 28, 3...  
2  [1, 4, 6, 9, 12, 14, 16, 17, 22, 23, 25, 28, 3...  

[3 rows x 53 columns]

In [219]:
def pred_cuda(test_df, model):
    #获得预测
    test_dataset = MyDataset(test_df, use_cols, target_cols, 0)
    test_loader = DataLoader(
        test_dataset,
        batch_size=1024*16,
        shuffle=False,
        drop_last=False,
        pin_memory=True
    )

    preds = []
    model.eval()
    with torch.no_grad():
        for data in tqdm(test_loader):
            pred = model(data['input'].to(device))
            preds.append(pred.detach().cpu().numpy())
    preds = np.concatenate(preds, 0)
    print(preds.shape)

    del test_dataset, test_loader, model;
    gc.collect()
    torch.cuda.empty_cache()
    return preds
        
def predict_sig(test_df, k=5, modelname=''):
    for target in range(8):        
        cols = []
        for fold_ in range(k):
            modelname1 = f'{modelname}_target{target}_{fold_}.pt'
            print(f'Model {modelname1}')
            model = CVPRModel(input_dim=93,
                        num_classes=8,
                        bi=True,
                        time_step=37
                       ).to(device)
            model.load_state_dict(torch.load(modelpath+modelname1))

            pred_ = pred_cuda(test_df, model)[:, target]
            tmp_c = f'{target_cols[target]}_{fold_}'
            test_df[tmp_c] = pred_
            cols.append(tmp_c)
            print(f'Done {tmp_c}')
            
        print(cols)
        test_df[cols] = test_df[cols].rank()
        test_df[target_cols[target]] = test_df[cols].mean(axis=1).rank()
        
def predict_all(test_df, k=5, modelname = f'lstm2y稠密_bc400_lr001_softsign'):

    print(f'Model {modelname}')

    cols = []
    for fold_ in range(k):
        model = CVPRModel(input_dim=1,
                    num_classes=8,
                    bi=True,
                    time_step=37
                   ).to(device)
        model.load_state_dict(torch.load(modelpath+f'{modelname}_{fold_}.pt'))

        pred_ = pred_cuda(test_df, model)
        tmp_c = [f'{target}_{fold_}' for target in target_cols]
        test_df[tmp_c] = pred_
        cols += tmp_c
    #get rank
    print(cols)
    test_df[cols] = test_df[cols].rank()
    for c in target_cols:
        test_df[c] = test_df[[f'{c}_{fold_}' for fold_ in range(k)]].mean(axis=1)
        test_df[c] = test_df[c].rank()

In [220]:
k, modelname

(5, 'lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe')

In [221]:
# LSTM_2layer_step37_kendall_8all_softrankloss
# LSTM_2layer_step37_kendall_8all_softsign
# LSTM_2layer_step37_kendall_8all_tanh


In [222]:
# train_df1 = train_df.copy()
# predict_sig(train_df1, k=5, modelname='lstm2y稠密_bc400_lr001_tanh_mat')
# compute_metric(train_df[target_cols].values, train_df1[target_cols].values)

In [225]:
test_df[[x+'_trans_y' for x in target_cols]]=np.nan

In [223]:
np.mean([0.37461616, 0.90014512, 0.91819605, 0.97460526, 0.92847466,
       0.72192225, 0.92732675, 0.83744911])

0.82284192

In [226]:
predict_sig(test_df, k=5, modelname='lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe')

Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target0_0.pt


C:\Users\45928\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:15: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  from ipykernel import kernelapp as app


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done cplfw_rank_0
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target0_1.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done cplfw_rank_1
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target0_2.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done cplfw_rank_2
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target0_3.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done cplfw_rank_3
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target0_4.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done cplfw_rank_4
['cplfw_rank_0', 'cplfw_rank_1', 'cplfw_rank_2', 'cplfw_rank_3', 'cplfw_rank_4']
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target1_0.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done market1501_rank_0
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target1_1.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done market1501_rank_1
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target1_2.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done market1501_rank_2
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target1_3.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done market1501_rank_3
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target1_4.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done market1501_rank_4
['market1501_rank_0', 'market1501_rank_1', 'market1501_rank_2', 'market1501_rank_3', 'market1501_rank_4']
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target2_0.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done dukemtmc_rank_0
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target2_1.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done dukemtmc_rank_1
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target2_2.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done dukemtmc_rank_2
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target2_3.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done dukemtmc_rank_3
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target2_4.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done dukemtmc_rank_4
['dukemtmc_rank_0', 'dukemtmc_rank_1', 'dukemtmc_rank_2', 'dukemtmc_rank_3', 'dukemtmc_rank_4']
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target3_0.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done msmt17_rank_0
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target3_1.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done msmt17_rank_1
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target3_2.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done msmt17_rank_2
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target3_3.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done msmt17_rank_3
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target3_4.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done msmt17_rank_4
['msmt17_rank_0', 'msmt17_rank_1', 'msmt17_rank_2', 'msmt17_rank_3', 'msmt17_rank_4']
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target4_0.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done veri_rank_0
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target4_1.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done veri_rank_1
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target4_2.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done veri_rank_2
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target4_3.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done veri_rank_3
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target4_4.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done veri_rank_4
['veri_rank_0', 'veri_rank_1', 'veri_rank_2', 'veri_rank_3', 'veri_rank_4']
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target5_0.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done vehicleid_rank_0
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target5_1.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done vehicleid_rank_1
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target5_2.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done vehicleid_rank_2
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target5_3.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done vehicleid_rank_3
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target5_4.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done vehicleid_rank_4
['vehicleid_rank_0', 'vehicleid_rank_1', 'vehicleid_rank_2', 'vehicleid_rank_3', 'vehicleid_rank_4']
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target6_0.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done veriwild_rank_0
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target6_1.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done veriwild_rank_1
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target6_2.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done veriwild_rank_2
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target6_3.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done veriwild_rank_3
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target6_4.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done veriwild_rank_4
['veriwild_rank_0', 'veriwild_rank_1', 'veriwild_rank_2', 'veriwild_rank_3', 'veriwild_rank_4']
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target7_0.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done sop_rank_0
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target7_1.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done sop_rank_1
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target7_2.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done sop_rank_2
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target7_3.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done sop_rank_3
Model lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_target7_4.pt


  0%|          | 0/7 [00:00<?, ?it/s]

(99500, 8)
Done sop_rank_4
['sop_rank_0', 'sop_rank_1', 'sop_rank_2', 'sop_rank_3', 'sop_rank_4']


In [227]:
# predict_all(test_df, k=5, modelname='lstm2y稠密_bc400_lr001_pair')

In [228]:
test_df[target_cols] = test_df[target_cols].astype(int)-1

In [229]:
test_df[target_cols].nunique()

cplfw_rank         91761
market1501_rank    91358
dukemtmc_rank      92086
msmt17_rank        92015
veri_rank          92005
vehicleid_rank     93083
veriwild_rank      92253
sop_rank           91416
dtype: int64

In [234]:
modelname

'lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_20220516'

In [235]:
modelname = 'lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_20220516'

In [232]:
#输出
for i in tqdm(test_df[['id']+target_cols].values):
    id_ = i[0]
    for k,v in enumerate(target_cols):
        k += 1
        test_data[id_][v] = i[k]
        
with open(f'./sub/{modelname}.json', 'w') as f:
    json.dump(test_data, f)

C:\Users\45928\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  


  0%|          | 0/99500 [00:00<?, ?it/s]

In [233]:
modelname

'lstm2y_加权_bc400_shuffle_lr001_tanh1_ohe_20220516'

In [265]:
1

1